### ISSUE TITLE
Drop down menu not visible if window not resized

### ISSUE THREAD

**Issue by dellie** [viljamis/responsive-nav.js#137]
Okay, so I'm calling on the plug-in twice.

First instance, it works fine (usual navigation method).

But, for my second instance here's what I'm doing...

After the user scrolls beyond a certain waypoint, a smaller, condensed version of my navigation drops down. If my window is above the break-point and I resize, the condensed version responds as it should AND the menu toggles perfectly.

However, if I load the page at the breakpoint size, the drop down menu doesn't work. But, if I resize my window above the breakpoint and then resize it back down, it will work. 

So, how do I make the drop down version work without the next to resize?

Does that make sense?

**Comment by evanfuture** [comment]
If anyone runs into this again, please note that it probably has to do with the Toggle element display property.  Its used to do a lot in this plugin, so if you (like me) have set your toggle element to display: none; in order to keep it from view, you'll have to find another way.  In my case, I hid the toggle elements, not the container, and that worked fine.  Hope that helps.
