### ISSUE TITLE
Max height doesn't account for padding on .nav-collapse

### ISSUE THREAD

**Issue by cporto** [viljamis/responsive-nav.js#95]
Max height calculation doesn't seem to account for additional padding added to the .nav-collapse css class.

responsive-nav.js Line 402:
savedHeight += nav.inner[i].offsetHeight;

Modified it to:

savedHeight += nav.inner[i].offsetHeight + window.getComputedStyle(nav.inner[i], null).getPropertyValue('padding');

This adds the missing padding and fixes the max height being set incorrectly.

**Comment by joshbiz** [comment]
Thanks @cporto 
I think your code variation worked for me too. Something somewhere has been screwing up my savedHeight value causing list items at the end to be hidden (only at particular screen widths). Gonna have to do a lot more fiddling around.
But great menu code, @viljamis

**Comment by joshbiz** [comment]
No, it doesn't work for me after all. There are a few screen widths where the max-height is incorrectly calculated and this causes some menu items to be hidden away from view. Sadly, I'm going to have to find an alternative menu system methinks. It's probably just the CSS I'm using for my menu doesn't work with the max-height calculation. Or it could be because I'm using a Typekit font maybe.
